spring:
  application:
    name: gitByCity
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gitByCity1
    username: postgres
    password: 123
  servlet:
    multipart:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /api

token:
  expired:
    access: 6000000
    refresh: 1296000000
  signing:
    key: Xz0bPHhol9lXJiL47I4F1rZNAbYGvxohjhAfardW8ugWAoBVpJnSme8CaGyFA6Gy

log4j:
  appender:
    FILE:
      encoding: UTF-8

app:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 150
  threadNamePrefix: AsyncTaskThread-

minio:
  bucket: imagesmy
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin