spring:
  application:
    name: gitByCity
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gitByCity1
    username: postgres
    password: 123

  servlet:
    multipart:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /api

token:
  signing:
    key: basebasebasebasebasebasebasebasebasebasebasebasebasebasebasebase

log4j:
  appender:
    FILE:
      encoding: UTF-8

app:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 150
  threadNamePrefix: AsyncTaskThread-

minio:
  bucket: imagesmy
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin